// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWHBZAnreowkF0SUOBczrdYp4s-jZUU2c',
    appId: '1:261781494:web:62ca28e42e0d5ef11779d7',
    messagingSenderId: '261781494',
    projectId: 'disco-party-8a6a0',
    authDomain: 'disco-party-8a6a0.firebaseapp.com',
    storageBucket: 'disco-party-8a6a0.firebasestorage.app',
    measurementId: 'G-XZZ2YRN27F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPrsKX7AskF2deIHF8YKCgiHDKIdavvlM',
    appId: '1:261781494:android:6899e907bc0f3ded1779d7',
    messagingSenderId: '261781494',
    projectId: 'disco-party-8a6a0',
    storageBucket: 'disco-party-8a6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBigi1SnLwpxCzIZLWSYehrDzKF2JXe7tU',
    appId: '1:261781494:ios:09ebd5ffcba9bb721779d7',
    messagingSenderId: '261781494',
    projectId: 'disco-party-8a6a0',
    storageBucket: 'disco-party-8a6a0.firebasestorage.app',
    iosBundleId: 'com.example.discoParty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBigi1SnLwpxCzIZLWSYehrDzKF2JXe7tU',
    appId: '1:261781494:ios:09ebd5ffcba9bb721779d7',
    messagingSenderId: '261781494',
    projectId: 'disco-party-8a6a0',
    storageBucket: 'disco-party-8a6a0.firebasestorage.app',
    iosBundleId: 'com.example.discoParty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWHBZAnreowkF0SUOBczrdYp4s-jZUU2c',
    appId: '1:261781494:web:7660dcc93b77d10d1779d7',
    messagingSenderId: '261781494',
    projectId: 'disco-party-8a6a0',
    authDomain: 'disco-party-8a6a0.firebaseapp.com',
    storageBucket: 'disco-party-8a6a0.firebasestorage.app',
    measurementId: 'G-W76NFJSLV4',
  );
}
